### ISSUE TITLE
countOverlapsSimple random tests

### ISSUE THREAD

**Issue by xuebingjie1990** [uvacobi/interval_basics#1]
`q` doesn't seem to be defined in the random tests (it's defined in the basic tests). should this line https://github.com/cphg/interval_basics/blob/main/tests/testDriver.R#L37
be `cos = countOverlapsSimple(fixedquery, dbdf)`?

**Comment by nleroy917** [comment]
Also ran into this

**Comment by nsheff** [comment]
yes I believe that's right
